### PR TITLE
Update README.md and setup.py for v2.1.0 release

### LINKED ISSUE #200: Release for v2.1.0
After all goals are completed, I will update the `setup.py` and `README.md`.

### PR DESCRIPTION
**Pull request by BECATRUE**
I updated the version from 2.0.2 to 2.1.0.

This closes #200.

### CODE REVIEW

**Comment by kangz12345** [comment]
Should we merge this into `develop` or `release`?

**Comment by BECATRUE** [comment]
First, we need to merge this into `develop` branch, and then merge `develop` into `release`, because `develop` branch should be the latest branch!

**Comment by kangz12345** [comment]
Okay then I will rename this PR!

**Review by kangz12345 — APPROVED** [review]
LGTM

**Pull request merged**
