### PR TITLE
Becatrue/165/background

### LINKED ISSUE #165: Add the logo as icon and background
### Feature you want to implement
The logo will be drawn in `self.centralWidget`.

### How the feature is implemented
- The background image is stored in `resources/background.png`.
- The implementation is referred to the [artiq dashboard](https://github.com/m-labs/artiq/blob/master/artiq/frontend/artiq_dashboard.py#L82).

### Additional context
Thanks for designing this "QIWIS" logo. @choiwh03 

<image width="30%" src="https://github.com/snu-quiqcl/qiwis/assets/76851886/6fd55f62-3224-4327-928c-fb66fb548e0b">

### PR DESCRIPTION
**Pull request by BECATRUE**
This PR will close #165.

I added the background image into `qiwi.centralWidget`.
Due to the limitation of 'PyQt', the ratio of the image could not be fixed, just stretched.

image

### CODE REVIEW

**Comment by BECATRUE** [comment]
Please review it. @kangz12345

**Comment by kangz12345** [comment]
Hmm.. sadly it looks quite ugly... 😂

How about bench-marking the [artiq dashboard](https://github.com/m-labs/artiq/blob/df15f53ee97558b31c23a3bbe93f32c14b18fe74/artiq/frontend/artiq_dashboard.py#L82)?
Its `MdiArea` paints the logo.

However, if you think it requires too much work, I am happy with the current implementation!

**Comment by BECATRUE** [comment]
> Hmm.. sadly it looks quite ugly... 😂
> 
> How about bench-marking the [artiq dashboard](https://github.com/m-labs/artiq/blob/df15f53ee97558b31c23a3bbe93f32c14b18fe74/artiq/frontend/artiq_dashboard.py#L82)? Its `MdiArea` paints the logo.
> 
> However, if you think it requires too much work, I am happy with the current implementation!

Oh, your idea looks much better!
But I think we need to start `iquip` project, so why don't we leave it like this for now and continue it later?
We can always apply `qiwis`'s updates to `iquip`!

**Comment by kangz12345** [comment]
> Oh, your idea looks much better! But I think we need to start `iquip` project, so why don't we leave it like this for now and continue it later? We can always apply `qiwis`'s updates to `iquip`!

Okay! Let's hold this PR for now.

**Comment by BECATRUE** [comment]
I'm going to reopen this later.

**Pull request closed without merging**
